# Keep all in alphabetical order
components:
  # src/
  src/OpenFeature.Contrib.Hooks.Otel:
    - bacherfl
    - toddbaert
    - askpt
  src/OpenFeature.Contrib.Providers.Flagd:
    - bacherfl
    - toddbaert
  src/OpenFeature.Contrib.Providers.GOFeatureFlag:
    - thomaspoignant
  src/OpenFeature.Contrib.Providers.Flagsmith:
    - vpetrusevici
    - matthewelwell
  src/OpenFeature.Contrib.Providers.ConfigCat:
    - luizbon
  src/OpenFeature.Contrib.Providers.FeatureManagement:
    - ericpattison
    - toddbaert
  src/OpenFeature.Contrib.Providers.Statsig:
    - jenshenneberg

  # test/
  test/OpenFeature.Contrib.Hooks.Otel.Test:
    - bacherfl
    - toddbaert
    - askpt
  test/OpenFeature.Contrib.Providers.Flagd.Test:
    - bacherfl
    - toddbaert
  test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test:
    - thomaspoignant
  test/OpenFeature.Contrib.Providers.Flagsmith.Test:
    - vpetrusevici
    - matthewelwell
  test/OpenFeature.Contrib.Providers.ConfigCat.Test:
    - luizbon
  test/OpenFeature.Contrib.Providers.FeatureManagement.Test:
    - ericpattison
    - toddbaert
  test/src/OpenFeature.Contrib.Providers.Statsig.Test:
    - jenshenneberg

ignored-authors:
  - renovate-bot
