# Keep all in alphabetical order
components:
  # src/
  src/OpenFeature.Contrib.Hooks.Otel:
    - bacherfl
    - toddbaert
    - askpt
  src/OpenFeature.Contrib.Providers.Flagd:
    - bacherfl
    - toddbaert
  src/OpenFeature.Contrib.Providers.GOFeatureFlag:
    - thomaspoignant
  src/OpenFeature.Contrib.Providers.Flagsmith:
    - vpetrusevici
    - matthewelwell

  # test/
  test/OpenFeature.Contrib.Hooks.Otel.Test:
    - bacherfl
    - toddbaert
    - askpt
  test/OpenFeature.Contrib.Providers.Flagd.Test:
    - bacherfl
    - toddbaert
  test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test:
    - thomaspoignant
  test/OpenFeature.Contrib.Providers.Flagsmith.Test:
    - vpetrusevici
    - matthewelwell

ignored-authors:
  - renovate-bot
