# Keep all in alphabetical order
components:
  # src/
  src/OpenFeature.Contrib.Providers.Flagd:
    - bacherfl
    - toddbaert
  src/OpenFeature.Contrib.Providers.GOFeatureFlag:
    - thomaspoignant
  src/OpenFeature.Contrib.Providers.Flagsmith:
    - vpetrusevici
    - matthewelwell
  src/OpenFeature.Contrib.Providers.ConfigCat:
    - luizbon
    - adams85
  src/OpenFeature.Contrib.Providers.FeatureManagement:
    - ericpattison
    - toddbaert
  src/OpenFeature.Contrib.Providers.Statsig:
    - jenshenneberg
    - lattenborough
  src/OpenFeature.Contrib.Providers.Flipt:
    - jeandreidc
    - markphelps

  # test/
  test/OpenFeature.Contrib.Providers.Flagd.Test:
    - bacherfl
    - toddbaert
  test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test:
    - thomaspoignant
  test/OpenFeature.Contrib.Providers.Flagsmith.Test:
    - vpetrusevici
    - matthewelwell
  test/OpenFeature.Contrib.Providers.ConfigCat.Test:
    - luizbon
    - adams85
  test/OpenFeature.Contrib.Providers.FeatureManagement.Test:
    - ericpattison
    - toddbaert
  test/src/OpenFeature.Contrib.Providers.Statsig.Test:
    - jenshenneberg
    - lattenborough
  test/src/OpenFeature.Contrib.Providers.Flipt.Test:
    - jeandreidc
    - markphelps

ignored-authors:
  - renovate-bot
