// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schema/v1/schema.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Schema.V1 {
  /// <summary>
  /// Service defines the exposed rpcs of flagd
  /// </summary>
  public static partial class Service
  {
    static readonly string __ServiceName = "schema.v1.Service";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveBooleanRequest> __Marshaller_schema_v1_ResolveBooleanRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveBooleanRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveBooleanResponse> __Marshaller_schema_v1_ResolveBooleanResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveBooleanResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveStringRequest> __Marshaller_schema_v1_ResolveStringRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveStringRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveStringResponse> __Marshaller_schema_v1_ResolveStringResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveStringResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveFloatRequest> __Marshaller_schema_v1_ResolveFloatRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveFloatRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveFloatResponse> __Marshaller_schema_v1_ResolveFloatResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveFloatResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveIntRequest> __Marshaller_schema_v1_ResolveIntRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveIntRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveIntResponse> __Marshaller_schema_v1_ResolveIntResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveIntResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveObjectRequest> __Marshaller_schema_v1_ResolveObjectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveObjectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.ResolveObjectResponse> __Marshaller_schema_v1_ResolveObjectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.ResolveObjectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Schema.V1.EventStreamResponse> __Marshaller_schema_v1_EventStreamResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Schema.V1.EventStreamResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Schema.V1.ResolveBooleanRequest, global::Schema.V1.ResolveBooleanResponse> __Method_ResolveBoolean = new grpc::Method<global::Schema.V1.ResolveBooleanRequest, global::Schema.V1.ResolveBooleanResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResolveBoolean",
        __Marshaller_schema_v1_ResolveBooleanRequest,
        __Marshaller_schema_v1_ResolveBooleanResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Schema.V1.ResolveStringRequest, global::Schema.V1.ResolveStringResponse> __Method_ResolveString = new grpc::Method<global::Schema.V1.ResolveStringRequest, global::Schema.V1.ResolveStringResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResolveString",
        __Marshaller_schema_v1_ResolveStringRequest,
        __Marshaller_schema_v1_ResolveStringResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Schema.V1.ResolveFloatRequest, global::Schema.V1.ResolveFloatResponse> __Method_ResolveFloat = new grpc::Method<global::Schema.V1.ResolveFloatRequest, global::Schema.V1.ResolveFloatResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResolveFloat",
        __Marshaller_schema_v1_ResolveFloatRequest,
        __Marshaller_schema_v1_ResolveFloatResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Schema.V1.ResolveIntRequest, global::Schema.V1.ResolveIntResponse> __Method_ResolveInt = new grpc::Method<global::Schema.V1.ResolveIntRequest, global::Schema.V1.ResolveIntResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResolveInt",
        __Marshaller_schema_v1_ResolveIntRequest,
        __Marshaller_schema_v1_ResolveIntResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Schema.V1.ResolveObjectRequest, global::Schema.V1.ResolveObjectResponse> __Method_ResolveObject = new grpc::Method<global::Schema.V1.ResolveObjectRequest, global::Schema.V1.ResolveObjectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResolveObject",
        __Marshaller_schema_v1_ResolveObjectRequest,
        __Marshaller_schema_v1_ResolveObjectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Schema.V1.EventStreamResponse> __Method_EventStream = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Schema.V1.EventStreamResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "EventStream",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_schema_v1_EventStreamResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Schema.V1.SchemaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Service</summary>
    [grpc::BindServiceMethod(typeof(Service), "BindService")]
    public abstract partial class ServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Schema.V1.ResolveBooleanResponse> ResolveBoolean(global::Schema.V1.ResolveBooleanRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Schema.V1.ResolveStringResponse> ResolveString(global::Schema.V1.ResolveStringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Schema.V1.ResolveFloatResponse> ResolveFloat(global::Schema.V1.ResolveFloatRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Schema.V1.ResolveIntResponse> ResolveInt(global::Schema.V1.ResolveIntRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Schema.V1.ResolveObjectResponse> ResolveObject(global::Schema.V1.ResolveObjectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task EventStream(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::Schema.V1.EventStreamResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Service</summary>
    public partial class ServiceClient : grpc::ClientBase<ServiceClient>
    {
      /// <summary>Creates a new client for Service</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Service that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveBooleanResponse ResolveBoolean(global::Schema.V1.ResolveBooleanRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveBoolean(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveBooleanResponse ResolveBoolean(global::Schema.V1.ResolveBooleanRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResolveBoolean, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveBooleanResponse> ResolveBooleanAsync(global::Schema.V1.ResolveBooleanRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveBooleanAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveBooleanResponse> ResolveBooleanAsync(global::Schema.V1.ResolveBooleanRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResolveBoolean, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveStringResponse ResolveString(global::Schema.V1.ResolveStringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveString(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveStringResponse ResolveString(global::Schema.V1.ResolveStringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResolveString, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveStringResponse> ResolveStringAsync(global::Schema.V1.ResolveStringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveStringAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveStringResponse> ResolveStringAsync(global::Schema.V1.ResolveStringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResolveString, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveFloatResponse ResolveFloat(global::Schema.V1.ResolveFloatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveFloat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveFloatResponse ResolveFloat(global::Schema.V1.ResolveFloatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResolveFloat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveFloatResponse> ResolveFloatAsync(global::Schema.V1.ResolveFloatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveFloatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveFloatResponse> ResolveFloatAsync(global::Schema.V1.ResolveFloatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResolveFloat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveIntResponse ResolveInt(global::Schema.V1.ResolveIntRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveInt(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveIntResponse ResolveInt(global::Schema.V1.ResolveIntRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResolveInt, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveIntResponse> ResolveIntAsync(global::Schema.V1.ResolveIntRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveIntAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveIntResponse> ResolveIntAsync(global::Schema.V1.ResolveIntRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResolveInt, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveObjectResponse ResolveObject(global::Schema.V1.ResolveObjectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveObject(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Schema.V1.ResolveObjectResponse ResolveObject(global::Schema.V1.ResolveObjectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResolveObject, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveObjectResponse> ResolveObjectAsync(global::Schema.V1.ResolveObjectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResolveObjectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Schema.V1.ResolveObjectResponse> ResolveObjectAsync(global::Schema.V1.ResolveObjectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResolveObject, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Schema.V1.EventStreamResponse> EventStream(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EventStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Schema.V1.EventStreamResponse> EventStream(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_EventStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ResolveBoolean, serviceImpl.ResolveBoolean)
          .AddMethod(__Method_ResolveString, serviceImpl.ResolveString)
          .AddMethod(__Method_ResolveFloat, serviceImpl.ResolveFloat)
          .AddMethod(__Method_ResolveInt, serviceImpl.ResolveInt)
          .AddMethod(__Method_ResolveObject, serviceImpl.ResolveObject)
          .AddMethod(__Method_EventStream, serviceImpl.EventStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ResolveBoolean, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Schema.V1.ResolveBooleanRequest, global::Schema.V1.ResolveBooleanResponse>(serviceImpl.ResolveBoolean));
      serviceBinder.AddMethod(__Method_ResolveString, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Schema.V1.ResolveStringRequest, global::Schema.V1.ResolveStringResponse>(serviceImpl.ResolveString));
      serviceBinder.AddMethod(__Method_ResolveFloat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Schema.V1.ResolveFloatRequest, global::Schema.V1.ResolveFloatResponse>(serviceImpl.ResolveFloat));
      serviceBinder.AddMethod(__Method_ResolveInt, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Schema.V1.ResolveIntRequest, global::Schema.V1.ResolveIntResponse>(serviceImpl.ResolveInt));
      serviceBinder.AddMethod(__Method_ResolveObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Schema.V1.ResolveObjectRequest, global::Schema.V1.ResolveObjectResponse>(serviceImpl.ResolveObject));
      serviceBinder.AddMethod(__Method_EventStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Schema.V1.EventStreamResponse>(serviceImpl.EventStream));
    }

  }
}
#endregion
