services:
  flagd:
    build:
      context: flagd-testbed
      dockerfile: flagd/Dockerfile
    ports:
      - 8013:8013
  flagd-unstable:
    build:
      context: flagd-testbed
      dockerfile: flagd/Dockerfile.unstable
    ports:
      - 8014:8013
  flagd-sync:
    build:
      context: flagd-testbed
      dockerfile: sync/Dockerfile
    ports:
      - 9090:9090
  flagd-sync-unstable:
    build:
      context: flagd-testbed
      dockerfile: sync/Dockerfile.unstable
    ports:
      - 9091:9090