using System.Collections.Generic;
using OpenFeature.Constant;
using OpenFeature.Model;

namespace OpenFeature.Contrib.Providers.Flagd;

/// <summary>
/// Represents an event generated by a provider to report changes in flag states and related synchronization metadata.
/// </summary>
/// <remarks>Use this class to receive detailed information about provider events, including which flags have
/// changed and any associated synchronization metadata. Instances of this class are typically created by the provider
/// and supplied to event handlers or listeners to notify consumers of relevant changes.</remarks>
public sealed class FlagdProviderEvent
{
    /// <summary>
    /// The type of provider event that occurred.
    /// </summary>
    public ProviderEventTypes EventType { get; }

    /// <summary>
    /// A list of flag keys that have changed.
    /// </summary>
    public List<string> FlagsChanged { get; }

    /// <summary>
    /// If available, metadata about the sync that triggered the event.
    /// </summary>
    public Structure SyncMetadata { get; }

    /// <summary>
    /// Initializes a new instance of the FlagdProviderEvent class with the specified event type, changed flags, and
    /// synchronization metadata.
    /// </summary>
    /// <param name="eventType">The type of provider event that occurred. Determines the nature of the event being reported.</param>
    /// <param name="flagsChanged">A list of flag names that have changed as a result of the event. If no flags have changed, an empty list is
    /// used.</param>
    /// <param name="syncMetadata">Metadata describing the synchronization state at the time of the event. If not provided, an empty structure is
    /// used.</param>
    public FlagdProviderEvent(ProviderEventTypes eventType, List<string> flagsChanged, Structure syncMetadata)
    {
        this.EventType = eventType;
        this.FlagsChanged = flagsChanged ?? new List<string>();
        this.SyncMetadata = syncMetadata ?? Structure.Empty;
    }
}
