name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build-test:
    runs-on: windows-latest

    strategy:
      matrix:
        version: [net462,net6.0,net7.0]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test ${{ matrix.version }}
      run: dotnet test --configuration Release --no-build --logger:"console;verbosity=detailed"
